steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/withcicd_study:latest'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/withcicd_study:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/withcicd_study:latest'

- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - "beta"
  - "run"
  - "deploy"
  - "withcicd_study"
  - "--image=gcr.io/$PROJECT_ID/withcicd_study"
  - "--platform=managed"
  - "--region=asia-northeast1"
  - "--allow-unauthenticated"
  - "--memory=64Mi"
  - "--service-account=cloudrunbuilder@clvflf-cloud-run-study.iam.gserviceaccount.com"  

